name = "NumCME"
uuid = "1785c143-4357-4f1f-be49-5c4bc10f803a"
authors = ["Huy D. Vo <vdhuy91@gmail.com> and contributors"]
version = "0.1.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ReusePatterns = "a39b5e78-89b5-562b-97d8-70689129df0c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
DataStructures = "0.18, 0.19"
DifferentialEquations = "7"
ForwardDiff = "0.10, 0.11"
LinearAlgebra = "1"
ModelingToolkit = "8"
ReusePatterns = "0.2, 0.3"
StaticArrays = "1"
Sundials = "4"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
